name: Check Package

on: 
  schedule:
    - cron: '0 * * * 5' # every friday AM 8:00

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - uses: MeilCli/npm-update-check-action@v4
      id: outdated
    - uses: 8398a7/action-slack@v2
      if: steps.outdated.outputs.has_npm_update != 'false'
      with:
        status: ${{ job.status }}
        text: ${{ steps.outdated.outputs.npm_update_text }}
        author_name: GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.CRREMOVE }}
