name: Node CI

on:
  workflow_run:
    workflows: ["Upgrade NPM packages"]
    types:
      - completed

jobs:
    lint:
        if: github.actor!= 'dependabot-preview[bot]'
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 18.x]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
            -   run: npm i -g pnpm
            -   run: pnpm -r install
            -   run: |
                  pnpm run lint
                  if [[ -n $(git status --porcelain) ]]; then
                     git config --global --add safe.directory /home/runner/work/panel-docker/panel-docker
                     git config --global user.name 'github-actions[bot]'
                     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                     git add -A
                     git commit -sam "fix(lint): NPM Fix Lint (automated)" || exit 0
                     git push --force
                  fi
                env:
                    CI: true
