name: Node CI

on:
  workflow_run:
    workflows: ["Upgrade NPM packages"]
    types:
      - completed

jobs:
    lint:
        if: github.actor!= 'dependabot-preview[bot]'
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 14.x, 16.x, 18.x]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
            -   run: npm i -g pnpm
            -   run: pnpm -r install
            -   run: pnpm run lint
                env:
                    CI: true
